"""empty message

Revision ID: 5b6c00c292fd
Revises: 
Create Date: 2020-12-10 18:50:40.230645

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5b6c00c292fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('login', sa.String(length=50), nullable=False),
                    sa.Column('password', sa.String(length=50), nullable=False),
                    sa.Column('username', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login'),
                    sa.UniqueConstraint('password'),
                    sa.UniqueConstraint('username')
                    )
    op.create_table('goods',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=500), nullable=False),
                    sa.Column('customer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['customer_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('customers',
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('goods_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
                    )
    op.create_table('statistics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('data', sa.DateTime(), nullable=True),
                    sa.Column('goods_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['goods_id'], ['goods.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    op.drop_table('customers')
    op.drop_table('goods')
    op.drop_table('user')
    # ### end Alembic commands ###
